# .goreleaser.yml
version: 2
project_name: terraform-provider-virakcloud
builds:
  - id: terraform-provider-virakcloud
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    main: .
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - id: terraform-provider-virakcloud
    formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    strip_binary_directory: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  ids:
    - terraform-provider-virakcloud

signs:
  - cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
    artifacts: checksum
    stdin: "{{ .Env.GPG_PASSPHRASE }}"
release:
  github:
    owner: virak-cloud
    name: terraform-provider-virak
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'